import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from '../../lib/api';
import type { Account, Contact, Journal, JournalEntry } from '../../lib/types';
import { formatDate, formatMoney, today, toDateInput } from '../../lib/format';
import { useList, useRecord } from '../../hooks/useList';
import { useToast } from '../../app/ToastContext';
import { FormShell, ListShell } from '../../components/shells';
import {
  ConfirmDialog,
  EmptyState,
  Field,
  Spinner,
  StatusBadge,
  TextInput,
  WarningBanner,
} from '../../components/ui';
import { RecordPicker } from '../../components/RecordPicker';

interface DraftLine {
  key: string;
  accountId: number | null;
  partnerId: number | null;
  label: string;
  debit: number;
  credit: number;
}

const emptyLine = (): DraftLine => ({
  key: Math.random().toString(36).slice(2),
  accountId: null,
  partnerId: null,
  label: '',
  debit: 0,
  credit: 0,
});

export function JournalEntriesPage() {
  const navigate = useNavigate();
  const list = useList<JournalEntry>('/journal-entries', { pageSize: 25 });

  return (
    <ListShell
      title="Journal Entries"
      subtitle="Manual entries plus every entry generated by a bill, invoice or payment."
      search={list.params.search ?? ''}
      onSearch={list.setSearch}
      searchPlaceholder="Search number, reference or partner"
      onNew={() => navigate('/account/journal-entries/new')}
      filters={
        <select
          className="input w-auto py-2"
          value={list.params.status ?? ''}
          onChange={(event) => list.setStatus(event.target.value || undefined)}
          aria-label="Status filter"
        >
          <option value="">All statuses</option>
          <option value="DRAFT">Draft</option>
          <option value="POSTED">Posted</option>
          <option value="CANCELLED">Cancelled</option>
        </select>
      }
      page={list.params.page}
      pageCount={list.pageCount}
      total={list.total}
      onPage={list.setPage}
    >
      {list.loading ? (
        <Spinner />
      ) : list.items.length === 0 ? (
        <EmptyState title="No journal entries yet" hint="Confirm a bill or invoice, or add one manually." />
      ) : (
        <div className="overflow-x-auto">
          <table className="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Number</th>
                <th>Partner</th>
                <th>Journal</th>
                <th className="text-right">Total</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {list.items.map((entry) => (
                <tr
                  key={entry.id}
                  className="cursor-pointer"
                  onClick={() => navigate(`/account/journal-entries/${entry.id}`)}
                >
                  <td>{formatDate(entry.date)}</td>
                  <td className="font-semibold text-slate-900">{entry.number}</td>
                  <td>{entry.partner?.name ?? '-'}</td>
                  <td>{entry.journal.name}</td>
                  <td className="text-right font-semibold">{formatMoney(entry.total)}</td>
                  <td>
                    <StatusBadge status={entry.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </ListShell>
  );
}

export function JournalEntryFormPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const toast = useToast();
  const { record, loading, reload } = useRecord<JournalEntry>('/journal-entries', id);

  const [header, setHeader] = useState({
    date: today(),
    journalId: null as number | null,
    reference: '',
    partnerId: null as number | null,
  });
  const [lines, setLines] = useState<DraftLine[]>([emptyLine(), emptyLine()]);
  const [busy, setBusy] = useState(false);
  const [confirmCancel, setConfirmCancel] = useState(false);

  const generated = Boolean(record && record.sourceType && record.sourceType !== 'MANUAL');
  const readOnly = generated || record?.status === 'POSTED' || record?.status === 'CANCELLED';

  useEffect(() => {
    if (!record) return;
    setHeader({
      date: toDateInput(record.date),
      journalId: record.journalId,
      reference: record.reference ?? '',
      partnerId: record.partnerId,
    });
    setLines(
      record.items.map((item) => ({
        key: String(item.id),
        accountId: item.accountId,
        partnerId: item.partnerId,
        label: item.label ?? '',
        debit: item.debit,
        credit: item.credit,
      })),
    );
  }, [record]);

  const totals = useMemo(() => {
    const debit = lines.reduce((sum, line) => sum + Number(line.debit || 0), 0);
    const credit = lines.reduce((sum, line) => sum + Number(line.credit || 0), 0);
    // An entry with nothing on it is not "balanced", it is simply empty.
    const hasAmounts = lines.some(
      (line) => line.accountId && (Number(line.debit) > 0 || Number(line.credit) > 0),
    );
    return {
      debit: Math.round(debit * 100) / 100,
      credit: Math.round(credit * 100) / 100,
      hasAmounts,
      balanced: hasAmounts && Math.round(debit * 100) === Math.round(credit * 100),
    };
  }, [lines]);

  const update = (key: string, patch: Partial<DraftLine>) =>
    setLines((current) => current.map((line) => (line.key === key ? { ...line, ...patch } : line)));

  const save = async (): Promise<JournalEntry | null> => {
    const payload = {
      date: header.date,
      journalId: header.journalId,
      reference: header.reference || null,
      partnerId: header.partnerId,
      lines: lines
        .filter((line) => line.accountId && (Number(line.debit) > 0 || Number(line.credit) > 0))
        .map((line) => ({
          accountId: line.accountId,
          partnerId: line.partnerId,
          label: line.label || null,
          debit: Number(line.debit) || 0,
          credit: Number(line.credit) || 0,
        })),
    };

    if (!payload.journalId) {
      toast.error('Choose a journal');
      return null;
    }
    if (payload.lines.length === 0) {
      toast.error('Add at least one line with an account and an amount');
      return null;
    }

    setBusy(true);
    try {
      if (record) {
        const { data } = await api.put<JournalEntry>(`/journal-entries/${record.id}`, payload);
        return data;
      }
      const { data } = await api.post<JournalEntry>('/journal-entries', payload);
      return data;
    } catch (error) {
      toast.error(errorMessage(error, 'Could not save the journal entry'));
      return null;
    } finally {
      setBusy(false);
    }
  };

  const post = async () => {
    const saved = await save();
    if (!saved) return;
    try {
      await api.post(`/journal-entries/${saved.id}/post`);
      toast.success(`${saved.number} posted`);
      navigate(`/account/journal-entries/${saved.id}`, { replace: true });
      if (record) await reload();
    } catch (error) {
      toast.error(errorMessage(error, 'Could not post the entry'));
    }
  };

  const cancel = async () => {
    setConfirmCancel(false);
    if (!record) {
      navigate('/account/journal-entries');
      return;
    }
    try {
      await api.post(`/journal-entries/${record.id}/cancel`);
      toast.success(`${record.number} cancelled`);
      await reload();
    } catch (error) {
      toast.error(errorMessage(error, 'Could not cancel the entry'));
    }
  };

  if (loading) return <Spinner />;

  return (
    <FormShell
      title={record ? record.number : 'New Journal Entry'}
      subtitle={
        generated
          ? `Generated by ${record?.sourceType?.replace('_', ' ').toLowerCase()} - view only`
          : 'Debit and credit must match before the entry can be posted.'
      }
      status={record ? <StatusBadge status={record.status} /> : null}
      backTo="/account/journal-entries"
      onNew={() => navigate('/account/journal-entries/new')}
      onConfirm={readOnly ? undefined : () => void post()}
      confirmLabel="Post"
      confirmDisabled={busy || !totals.balanced}
      actions={
        record && record.status !== 'CANCELLED' && !generated ? (
          <button type="button" className="btn-secondary" onClick={() => setConfirmCancel(true)}>
            Cancel
          </button>
        ) : null
      }
      banner={
        !readOnly && totals.hasAmounts && !totals.balanced ? (
          <WarningBanner>
            Total debit {formatMoney(totals.debit)} does not equal total credit{' '}
            {formatMoney(totals.credit)}. Balance the entry before posting.
          </WarningBanner>
        ) : null
      }
    >
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Field label="Accounting Date">
          <TextInput
            type="date"
            value={header.date}
            disabled={readOnly}
            onChange={(event) => setHeader({ ...header, date: event.target.value })}
          />
        </Field>
        <Field label="Journal">
          <RecordPicker<Journal>
            endpoint="/journals"
            value={header.journalId}
            disabled={readOnly}
            onChange={(journalId) => setHeader({ ...header, journalId })}
            placeholder="Select a journal"
          />
        </Field>
        <Field label="Reference">
          <TextInput
            value={header.reference}
            disabled={readOnly}
            onChange={(event) => setHeader({ ...header, reference: event.target.value })}
            placeholder="Reference"
          />
        </Field>
        <Field label="Partner">
          <RecordPicker<Contact>
            endpoint="/contacts"
            value={header.partnerId}
            disabled={readOnly}
            onChange={(partnerId) => setHeader({ ...header, partnerId })}
            placeholder="Select a partner"
          />
        </Field>
      </div>

      <div className="mt-6 overflow-x-auto rounded-lg border border-slate-200">
        <table className="table">
          <thead>
            <tr>
              <th className="min-w-[200px]">Account</th>
              <th className="min-w-[180px]">Partner</th>
              <th className="min-w-[160px]">Label</th>
              <th className="w-36 text-right">Debit</th>
              <th className="w-36 text-right">Credit</th>
              {readOnly ? null : <th className="w-12" />}
            </tr>
          </thead>
          <tbody>
            {lines.map((line) => (
              <tr key={line.key}>
                <td>
                  <RecordPicker<Account>
                    endpoint="/accounts"
                    value={line.accountId}
                    disabled={readOnly}
                    onChange={(accountId) => update(line.key, { accountId })}
                    placeholder="Account"
                  />
                </td>
                <td>
                  <RecordPicker<Contact>
                    endpoint="/contacts"
                    value={line.partnerId}
                    disabled={readOnly}
                    onChange={(partnerId) => update(line.key, { partnerId })}
                    placeholder="Partner"
                  />
                </td>
                <td>
                  <TextInput
                    value={line.label}
                    disabled={readOnly}
                    onChange={(event) => update(line.key, { label: event.target.value })}
                  />
                </td>
                <td>
                  <TextInput
                    type="number"
                    min={0}
                    step="0.01"
                    className="text-right"
                    value={line.debit}
                    disabled={readOnly}
                    onChange={(event) =>
                      update(line.key, { debit: Number(event.target.value), credit: 0 })
                    }
                  />
                </td>
                <td>
                  <TextInput
                    type="number"
                    min={0}
                    step="0.01"
                    className="text-right"
                    value={line.credit}
                    disabled={readOnly}
                    onChange={(event) =>
                      update(line.key, { credit: Number(event.target.value), debit: 0 })
                    }
                  />
                </td>
                {readOnly ? null : (
                  <td>
                    <button
                      type="button"
                      className="btn-ghost px-2 py-1 text-rose-600"
                      aria-label="Remove line"
                      onClick={() =>
                        setLines((current) =>
                          current.length > 1
                            ? current.filter((item) => item.key !== line.key)
                            : current,
                        )
                      }
                    >
                      &times;
                    </button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="bg-slate-50 font-bold">
              <td colSpan={3} className="px-3 py-2.5 text-right text-slate-600">
                Totals
              </td>
              <td className="px-3 py-2.5 text-right">{formatMoney(totals.debit)}</td>
              <td className="px-3 py-2.5 text-right">{formatMoney(totals.credit)}</td>
              {readOnly ? null : <td />}
            </tr>
          </tfoot>
        </table>
      </div>

      {readOnly ? null : (
        <button
          type="button"
          className="btn-secondary mt-3"
          onClick={() => setLines((current) => [...current, emptyLine()])}
        >
          Add a line
        </button>
      )}

      <ConfirmDialog
        open={confirmCancel}
        title="Cancel journal entry"
        message="A cancelled entry stays in the history but is excluded from every report."
        confirmLabel="Cancel entry"
        onConfirm={() => void cancel()}
        onCancel={() => setConfirmCancel(false)}
      />
    </FormShell>
  );
}
