import type { Tx } from '../lib/prisma';
import { badRequest } from '../lib/errors';
import { nextNumber } from '../lib/sequence';
import { checkBalance, type DraftItem } from '../domain/journal';

/**
 * Everything that turns a confirmed business document into a posted journal
 * entry. Callers run these inside a Prisma `$transaction`, so a document can
 * never end up confirmed without its entry (or the other way round).
 */

export const SYSTEM_ACCOUNTS = {
  bank: { name: 'Bank A/c', type: 'BANK' },
  cash: { name: 'Cash A/c', type: 'CASH' },
  debtors: { name: 'Debtors A/c', type: 'ASSET' },
  creditors: { name: 'Creditors A/c', type: 'LIABILITY' },
  salesIncome: { name: 'Sales Income A/c', type: 'INCOME' },
  purchaseExpense: { name: 'Purchase Expense A/c', type: 'EXPENSE' },
  otherExpense: { name: 'Other Expense A/c', type: 'OTHER_EXPENSE' },
  capital: { name: 'Capital A/c', type: 'CAPITAL' },
  taxPayable: { name: 'Tax Payable A/c', type: 'LIABILITY' },
} as const;

export type SystemAccountKey = keyof typeof SYSTEM_ACCOUNTS;

/**
 * Resolve one of the pre-configured accounts. The seeded name is preferred; if
 * it was renamed we fall back to the first account of the right type so posting
 * keeps working.
 */
export async function systemAccountId(tx: Tx, key: SystemAccountKey): Promise<number> {
  const spec = SYSTEM_ACCOUNTS[key];
  const byName = await tx.account.findFirst({ where: { name: spec.name } });
  if (byName) return byName.id;

  const byType = await tx.account.findFirst({
    where: { type: spec.type, isArchived: false },
    orderBy: { id: 'asc' },
  });
  if (byType) return byType.id;

  throw badRequest(
    `The Chart of Account "${spec.name}" is missing. Run the seed so the pre-configured accounts exist.`,
  );
}

export async function journalIdByType(
  tx: Tx,
  type: 'SALES' | 'PURCHASE' | 'BANK' | 'CASH',
): Promise<number> {
  const journal = await tx.journal.findFirst({ where: { type }, orderBy: { id: 'asc' } });
  if (!journal) {
    throw badRequest(`The ${type.toLowerCase()} journal is missing. Run the seed to create it.`);
  }
  return journal.id;
}

export interface PostEntryInput {
  date: Date;
  journalId: number;
  reference?: string | null;
  partnerId?: number | null;
  items: DraftItem[];
  sourceType: 'VENDOR_BILL' | 'CUSTOMER_INVOICE' | 'PAYMENT' | 'MANUAL';
  sourceId?: number | null;
  /**
   * System generated entries carry the number of the document that produced
   * them (Bill/2026/0001), manual entries get a JE/2026/0001 number.
   */
  number?: string;
}

/** Create a posted, balanced journal entry. */
export async function postEntry(tx: Tx, input: PostEntryInput) {
  const balance = checkBalance(input.items);
  if (!balance.balanced) {
    throw badRequest(
      `Journal entry is not balanced: debit ${balance.totalDebit.toFixed(2)} does not equal credit ${balance.totalCredit.toFixed(2)}`,
    );
  }
  if (input.items.length === 0) {
    throw badRequest('A journal entry needs at least one line');
  }

  const number = input.number ?? (await nextNumber(tx, 'JOURNAL_ENTRY', input.date));

  return tx.journalEntry.create({
    data: {
      number,
      date: input.date,
      journalId: input.journalId,
      reference: input.reference ?? null,
      partnerId: input.partnerId ?? null,
      status: 'POSTED',
      sourceType: input.sourceType,
      sourceId: input.sourceId ?? null,
      items: {
        create: input.items.map((item) => ({
          accountId: item.accountId,
          partnerId: item.partnerId ?? null,
          label: item.label ?? null,
          debit: item.debit,
          credit: item.credit,
        })),
      },
    },
    include: { items: true },
  });
}

/**
 * Reversing a document (Reset to Draft / Cancel) cancels its entry rather than
 * deleting it, so the audit trail survives. A cancelled entry is excluded from
 * every report.
 */
export async function cancelEntry(tx: Tx, entryId: number | null | undefined): Promise<void> {
  if (!entryId) return;
  await tx.journalEntry.update({ where: { id: entryId }, data: { status: 'CANCELLED' } });
}

/** Cancel every entry generated by a given source document. */
export async function cancelEntriesForSource(
  tx: Tx,
  sourceType: PostEntryInput['sourceType'],
  sourceId: number,
): Promise<void> {
  await tx.journalEntry.updateMany({
    where: { sourceType, sourceId, status: 'POSTED' },
    data: { status: 'CANCELLED' },
  });
}
